### PR TITLE
Bugfixes for ScrollController and improvements to compatibly with CupertinoApp/WidgetsApp 

### LINKED ISSUE #6: ScrollController not attached to any scroll views
Hi. First of all, thank you for this awesome library.
I've encountered an issue. When I ignore `scrollController`, which is passed as the second argument in `build` function, and my page uses any widget with its own scroll controller. I get this exception: 
`VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.`

Here is the code:
```dart
import 'package:flutter/material.dart';
import 'package:modal_bottom_sheet/modal_bottom_sheet.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      onGenerateRoute: (settings) {
        return MaterialWithModalsPageRoute(builder: (_) => MyHomePage());
      },
      initialRoute: '/',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      // home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Title'),
      ),
      body: Center(child: Container()),
      floatingActionButton: FloatingActionButton(
        onPressed: () => showCupertinoModalBottomSheet(
            context: context,
            builder: (context, _) => Scaffold(
                  body: Center(
                    child: TextField(),
                  ),
                )),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}
```
[Here](https://github.com/siemarell/scroll_view_bug_example) is example repo 
Steps to reproduce:
1. Run the app
2. Click on the floating action button to open modal view
3. Click on the text input

As far as I can understand, every scroll controller has to be attached to some widget. When we focus on text input, all scroll controllers are triggered, even the one, passed via build function. It is not attached, so I get an error.
As a workaround, I've created a dummy widget and attach the controller to it.
In my opinion, this should be done internally in the library

### PR DESCRIPTION
**Pull request by bierbaumtim**
This fixes #6 .

Also I fixed some issues when using CupertinoBottomSheet and BottomSheetRoute without having Material widget in the widget tree. The CupertinoBottomSheet has an assertion to MaterialLocalizations which not needed at every time. Therefore I've added a check if the root is a MaterialApp, if it is, the package works as before this PR. If not I assume that the root widget is a CupertinoApp and use default values, because, if I'm not wrong, the CupertinoLocalizations does not contains the needed values.

So this PR makes it possible to use the CupertinoBottomSheet in an CupertinoApp.

### CODE REVIEW

**Comment by jamesblasco** [comment]
Thanks for the PR, I will check tomorrow about MaterialLocalizations. Part of the code comes from the original showModalBottomSheet and there are things I haven't checked yet. Accessibility is one of them and if I don't remember wrong that is why MaterialLocalizations is used no?.

**Comment by bierbaumtim** [comment]
Thats right, but inside a CupertinoApp the MaterialLocalizations isn't available. I don't know how localization and accessibility works, but it can not depend on Material things because they not available. Therefore I only changed the code in that way, that if MaterialApp is the root, everything should work fine and if a WidgetApp or CupertinoApp is the root, some default values are used.

File: lib/src/bottom_sheets/cupertino_bottom_sheet.dart [hunk 1]
```diff
@@ -264,7 +275,12 @@ class CupertinoScaffold extends StatefulWidget {
     assert(useRootNavigator != null);
     assert(enableDrag != null);
     assert(debugCheckHasMediaQuery(context));
-    assert(debugCheckHasMaterialLocalizations(context));
+    final isCupertinoApp = Theme.of(context, shadowThemeOnly: true) == null;
```
Comment (jamesblasco) [inline lib/src/bottom_sheets/cupertino_bottom_sheet.dart:278]: I am not sure this is a great way to check if an app uses CupertinoApp,
You could do this and it would keep throwing the error
```dart
Theme(
   data: ThemeData(), 
   child: CupertinoApp(...),
);
```

I think using this would be better:
```dart
final hasMaterialLocalizations = Localizations.of<MaterialLocalizations>(context, MaterialLocalizations) != null;
final  barrierLabel = hasMaterialLocalizations ? MaterialLocalizations.of(context).modalBarrierDismissLabel : '';
```

File: lib/src/bottom_sheets/cupertino_bottom_sheet.dart [hunk 2]
```diff
@@ -4,10 +4,15 @@
 
 import 'dart:async';
 
-import 'package:flutter/cupertino.dart';
+import 'package:flutter/cupertino.dart' show CupertinoTheme;
 import 'package:flutter/foundation.dart';
 import 'package:flutter/gestures.dart';
-import 'package:flutter/material.dart';
+import 'package:flutter/material.dart'
```
Comment (jamesblasco) [inline lib/src/bottom_sheets/cupertino_bottom_sheet.dart:10]: Why is `show` needed? There is no conflicts between both libraries no?

File: lib/src/bottom_sheet_route.dart [hunk 3]
```diff
@@ -32,17 +32,22 @@ class _ModalBottomSheet<T> extends StatefulWidget {
...
-    final platform = Theme.of(context).platform;
-    switch (platform) {
-      case TargetPlatform.iOS:
-        return '';
-      case TargetPlatform.android:
-      case TargetPlatform.fuchsia:
-        return localizations.dialogLabel;
-        break;
+  String _getRouteLabel() {
+    if (Theme.of(context, shadowThemeOnly: true) == null) {
```
Comment (jamesblasco) [inline lib/src/bottom_sheet_route.dart:36]: Nice! Maybe instead of checking `if(Theme.of(context, shadowThemeOnly: true) == null)`
do this in line 39
`final platform = Theme.of(context)?.platform ?? defaultTargetPlatform;`

File: lib/src/bottom_sheets/cupertino_bottom_sheet.dart (hunk 2 above)
Comment (bierbaumtim) [reply lib/src/bottom_sheets/cupertino_bottom_sheet.dart:10]: That's right. 
My intention is to prevent further problems when using material widgets or parts of the material library without having checked if this could cause problems if the material is not in the WidgetTree.

File: lib/src/bottom_sheets/cupertino_bottom_sheet.dart (hunk 1 above)
Comment (bierbaumtim) [reply lib/src/bottom_sheets/cupertino_bottom_sheet.dart:278]: You're right. I didn't test this combination. 
I will replace my implementation with yours.

File: lib/src/bottom_sheet_route.dart (hunk 3 above)
Comment (bierbaumtim) [reply lib/src/bottom_sheet_route.dart:36]: Same here, I did not test the combination:
```
Theme(
   data: ThemeData(),
   child: CupertinoApp(...),
)
```

I tested your suggestion and works well. Maybe we should a comment, that using this package with an CupertinoApp or WidgetApp and testing on an Android Emulator requires to set `debugDefaultTargetPlatformOverride = TargetPlatform.iOS;`.

Comment (jamesblasco) [reply lib/src/bottom_sheet_route.dart:36]: Yeah, or instead of the assert just check ( Localizations.of<MaterialLocalizations>(context, MaterialLocalizations) != null); when TargetPlatform is Android. 

Overriding the default Target Platform is advise against and it is built only for testing.

Comment (bierbaumtim) [reply lib/src/bottom_sheet_route.dart:36]: The check would be a nice way I think. But I have a question, should we use `DefaultMaterialLocalizations().dialogLabel` as default value ifLocalizations are not available ?
So the implemetation would be as follows:
```
String _getRouteLabel() {
    final platform = Theme.of(context)?.platform ?? defaultTargetPlatform;
    switch (platform) {
      case TargetPlatform.iOS:
        return '';
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        if (Localizations.of(context, MaterialLocalizations) != null) {
          return MaterialLocalizations.of(context).dialogLabel;
        } else {
          return DefaultMaterialLocalizations().dialogLabel;
        }
    }
    return null;
  }
```

Comment (jamesblasco) [reply lib/src/bottom_sheet_route.dart:36]: Sounds good to me 👍

File: lib/src/bottom_sheet.dart [hunk 4]
```diff
@@ -231,7 +231,8 @@ class _ModalBottomSheetState extends State<ModalBottomSheet>
   void _handleScrollUpdate(ScrollNotification notification) {
     if (notification.metrics.pixels <= notification.metrics.minScrollExtent) {
       //Check if listener is same from scrollController
-      if (_scrollController.position.pixels != notification.metrics.pixels) {
+      if (_scrollController.hasClients &&
```
[the remark this answers is not in the document]
Comment (bierbaumtim) [reply lib/src/bottom_sheet.dart:234]: I wouldn't change the widget tree either.

Currently did not get what would not work with my change, but I added your line to the code.

[the remark this answers is not in the document]
Comment (jamesblasco) [reply lib/src/bottom_sheet.dart]: Because _handleScrollUpdate should only work when _scrollController is the one scrolling. 
That is why i use this  if (_scrollController.position.pixels != notification.metrics.pixels)
If the position of the scroller i no the one of the notification return and don't continue.

If you add _scrollController.hasClients there, the scrollController is not attached and there is another one scrolling: it would still call the code below

**Comment by jamesblasco** [comment]
LGTM! Do you plan to edit something else or should I merge it?

**Comment by bierbaumtim** [comment]
I'm done. You can merge it.

**Comment by jamesblasco** [comment]
Thank you!! You did an awesome job here 🙂
